apiVersion: v1
kind: ConfigMap
metadata:
  name: ecifm-bridge-config
data:
  MAS_BASE_URL: "https://main.facilities.inst1.apps.npos2.ecifmdev.net"
  MAS_CONTEXT: "/tririga"
  MAS_REDIRECT_URL: "https://main.facilities.inst1.apps.npos2.ecifmdev.net/app/tririga"
  MAS_REST_API: "/html/en/default/rest/SSOConnect?userName={0}&adGroupName={1}"
  JWT_ISSUER_URI: "https://login.microsoftonline.com/c99cc570-ba4f-474e-897d-22255a3cecd7/v2.0"
  BRIDGE_ISSUER_URL: "https://ecifm-sso-bridge-ecifm-sso-bridge.apps.npos2.ecifmdev.net"
  MAS_OIDC_CLIENT_ID: "mas-facilities"
  MAS_OIDC_REDIRECT_URI: "https://main.facilities.inst1.apps.npos2.ecifmdev.net/oidcclient/redirect/facilities"
  MAS_OAUTH_CLIENT_REDIRECT_URI: "https://auth.inst1.apps.npos2.ecifmdev.net/oidcclient/redirect/default-oidc"
  GRAPH_API_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: "openshift"
  AZURE_CLIENT_ID: "cbcea157-2c35-4ce3-b86c-782282e00857"
  TRIRIGA_USERNAME: "tarun.suneja@ecifm.com"
