apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ecifm-sso-bridge
  labels:
    app: ecifm-sso-bridge
spec:
  host: ecifm-sso-bridge-ecifm-sso-bridge.apps.npos2.ecifmdev.net
  path: /
  to:
    kind: Service
    name: ecifm-sso-bridge
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
