apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ecifm-saml-bridge
  namespace: tririga
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  host: bridge.apps.ocp.example.com
  to:
    kind: Service
    name: ecifm-saml-bridge
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
